version: "3.8"
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wpfiles:/var/www/html
    extra_hosts:
      - "totaisei.42.fr:127.0.0.1"
    networks:
      - inception_network
    restart: on-failure
    init: true

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000"
    volumes:
      - wpfiles:/var/www/html
    extra_hosts:
      - "totaisei.42.fr:127.0.0.1"
    env_file:
      - .env
    networks:
      - inception_network
    restart: on-failure
    init: true

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - wpdatabase:/var/lib/mysql
    ports:
      - "3306"
    env_file:
      - .env
    networks:
      - inception_network
    restart: on-failure
    init: true

networks:
  inception_network:
    driver: bridge

volumes:
  wpdatabase:
    driver_opts:
      type: none
      device: /home/totaisei/data/db
      o: bind
  wpfiles:
    driver_opts:
      type: none
      device: /home/totaisei/data/wp
      o: bind
