version: "3"
services:
  nginx:
    build: ./srcs/nginx
    image: nginx
    container_name: nginx
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:443:443"
    depends_on:
      - wordpress
    volumes:
      - /home/totaisei/data/wp:/var/www/html
  wordpress:
    build: ./srcs/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000"
    volumes:
      - /home/totaisei/data/wp:/var/www/html
  mariadb:
    build: ./srcs/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - /home/totaisei/data/db:/var/lib/mysql
    ports:
      - "3306"
