version: "3"
services:
  nginx:
    build: ./srcs/nginx
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - /home/totaisei/data/wp:/var/www/html
    extra_hosts:
      - "${DOMAIN_NAME}:127.0.0.1"
    networks:
      - inception_network

  wordpress:
    build: ./srcs/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000"
    volumes:
      - /home/totaisei/data/wp:/var/www/html
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
      WP_ADMIN_LOGIN: "${WP_ADMIN_LOGIN}"
      WP_ADMIN_PASS: "${WP_ADMIN_PASS}"
      WP_ADMIN_EMAIL: "${WP_ADMIN_EMAIL}"
      WP_USER_LOGIN_1: "${WP_USER_LOGIN_1}"
      WP_USER_PASS_1: "${WP_USER_PASS_1}"
      WP_USER_EMAIL_1: "${WP_USER_EMAIL_1}"
      WP_USER_LOGIN_2: "${WP_USER_LOGIN_2}"
      WP_USER_PASS_2: "${WP_USER_PASS_2}"
      WP_USER_EMAIL_2: "${WP_USER_EMAIL_2}"
      WP_DB_NAME: "${WP_DB_NAME}"
      WP_DB_USER: "${WP_DB_USER}"
      WP_DB_PASS: "${WP_DB_PASS}"
    networks:
      - inception_network

  mariadb:
    build: ./srcs/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - /home/totaisei/data/db:/var/lib/mysql
    ports:
      - "3306"
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
      WP_DB_NAME: "${WP_DB_NAME}"
      WP_DB_USER: "${WP_DB_USER}"
      WP_DB_PASS: "${WP_DB_PASS}"
      DB_USER_NAME_1: "${DB_USER_NAME_1}"
      DB_USER_PASS_1: "${DB_USER_PASS_1}"
      DB_USER_NAME_2: "${DB_USER_NAME_2}"
      DB_USER_PASS_2: "${DB_USER_PASS_2}"
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge
